language: generic

sudo: required

script:
    - git clone https://github.com/uqbar-project/wollok-cli
    - git checkout relativePath
    - chmod 777 ./wollok-cli/runTests.sh
    - export PATH="$PATH:/wollok-cli"
    - echo $PATH
    - runTests.sh
    