language: generic

sudo: required

script:
    - git clone git@github.com:uqbar-project/wollok-cli.git
    - git checkout relativePath
    - chmod 777 ./wollok-cli/runTests.sh
    - export PATH="$PATH:/wollok-cli/"
    - echo $PATH
    - runTests.sh
    